Thomvis/BrightFutures

BrightFutures/Future.swift, BrightFutures/FutureUtils.swift, BrightFuturesTests/BrightFuturesTests.swift
Changed NoSuchElementError to be an error code, and introduced BrightFuturesErrorDomain as the domain for NSErrors.
=> Fixed NSError domain and code

BrightFutures/Future.swift
I’m honestly not sure if this is the right answer, but I wanted to get back up and running with Swift 1.2b.
=> Remove use of @autoclosure

BrightFutures.xcodeproj/project.pbxproj, BrightFutures/ExecutionContext.swift, BrightFutures/Future.swift, BrightFutures/FutureUtils.swift, BrightFutures/InvalidationToken.swift, BrightFuturesTests/BrightFuturesTests.swift, BrightFuturesTests/InvalidationTokenTests.swift, README.md
With invalidation tokens, one can invalidate a callback chain if it is no longer relevant. 
The motivating example can be found here: https://gist.github.com/Thomvis/90bf499a2d7f65d37f3c
=> [WIP] Added invalidation tokens

BrightFutures/Future.swift, BrightFuturesTests/BrightFuturesTests.swift, README.md
This is a minimal set of changes to get current master to compile on official XCode 6.1.1 and Swift 1.1. 
Fixes #31 and as described in the issue report I suggest that Swift 1.2 support is moved to a separate branch and master branch works against official XCode version.
Not tested extensively, but logic tests pass on a simulator and a real project that was previously using 1.0.0.beta2 compiles and works against this branch both in a simulator and a device. (compiled with XCode Version 6.1.1 (6A2008a) and Swift 1.1.)
=> Back to swift 1.1

BrightFutures/Future.swift, BrightFutures/Queue.swift, BrightFutures/Semaphore.swift
Hi there, I love the BrightFutures library and I love some of the dispatch wrapper classes that are defined in it and i'd love to use them in my own code.
So I've:
- Made the `Semaphore` wrapper class public and renamed it's private `semaphore` property `underlyingSemaphore` and made it publicly readable/readwrite internally.
- Made the `dispatchTime` computed property of the already public `TimeInterval` enum public.
- Made the private `queue` property of the `Queue` struct publicly readable/readwrite internally and renamed it `underlyingQueue`
My reasons for naming the private semaphore/queue as underlyingSemaphore/queue was because when defining one of them someone will generally write: 
```swift
let queue = Queue()
``` 
then when using the underlying queue have to write 
```swift …
```
=> Access modifier changes.

BrightFutures/Queue.swift
Hi there, I noticed today that during the rename of the `queue` property of the Queue struct `underlyingQueue` in #38, I did not fix the comments referring to `self.queue`, i've done that in this PR.
=> Fixing Queue comments

BrightFutures/Future.swift, BrightFuturesTests/BrightFuturesTests.swift
Hi @Thomvis 
I think we shouldn't use a default value for the ExecutionContext parameter in flatMap method.
Because we will not be able to pass a function to the flatMap method as the following:
```
func foo(x: Int) -> Future<String, Error> {
}
let f = future(1)
f.flatMap(foo)     // error at here
```
=> using 2 separate methods instead of default ExecutionContext parameter

BrightFutures/AsyncType.swift
This minor change fixes a warning that springs up in Xcode 7.1 beta 2 (7B75) on the `swift-2.0` branch:
=> Implement Xcode 7.1 explicit capture semantics

BrightFutures/AsyncType.swift
AsyncType.forced() without a timeout is guaranteed to return a non-nil value, so it would be helpful to not require unwrapping at the call site.
=> Force unwrap optional for forced without timeout

BrightFutures/AsyncType+ResultType.swift
Previously, if !future.isCompleted, then future.isFailure was always true.  Futures shouldn't be neither success nor failure until completed.
=> incomplete Futures are not failed

BrightFutures/SequenceType+BrightFutures.swift
Apparantly not crashing with Swift 2.2. Tested on iOS Simulator and OS X.
=> Remove the not-nice `as!` cast in .sequence().

BrightFutures/AsyncType.swift, BrightFuturesTests/BrightFuturesTests.swift
Hey, it was surprising that `delay()` operated in parallel, eg
let t0 = CACurrentMediaTime()
future { return }
.delay(1)
.andThen { _ in print("\(CACurrentMediaTime() - t0) sec" }
.delay(1)
.andThen { _ in print("\(CACurrentMediaTime() - t0) sec" }
yields
1 sec
1 sec
This pull request modifies `delay()` so that the above example yields
1 sec
2 sec
I'm new to the library, so feel free to suggest changes or reject. Thanks!
=> Chain AsyncType.delay() sequentially rather than in parallel

BrightFutures.xcodeproj/project.pbxproj, BrightFutures/Async.swift, BrightFutures/AsyncType+ResultType.swift, BrightFutures/AsyncType.swift, BrightFutures/Dispatch+BrightFutures.swift, BrightFutures/ExecutionContext.swift, BrightFutures/Future.swift, BrightFutures/InvalidationToken.swift, BrightFutures/MutableAsyncType.swift, BrightFutures/Promise.swift, BrightFutures/Result+BrightFutures.swift, BrightFutures/SequenceType+BrightFutures.swift, BrightFuturesTests/BrightFuturesTests.swift, BrightFuturesTests/QueueTests.swift, Cartfile, Cartfile.resolved
`public` methods have been converted to `open` as per the Xcode migrator
to maintain external compatibility however moving to the new `public`
access level may be ultimately desirable.
=> Update for Xcode 8 beta 6

BrightFutures.xcodeproj/project.pbxproj, BrightFutures/AsyncType+Debug.swift, BrightFutures/AsyncType+ResultType.swift, BrightFutures/AsyncType.swift, BrightFuturesTests/FutureDebugTests.swift
This pull request adds possibility to debug the results of `AsyncType`.
`AsyncType` can be logged in 2 ways:
1. By providing identifier and the log message with be generated automatically
2. By providing closure that will generate log message
What is more, I added `LoggerType` protocol for 2 reasons:
1. If someone would like to provide custom logger
2. To make unit testing nice and easy
I also created an internal extension on String to provide `lastPathComponent` as I didn't want to use `NSString`. All the test data for lastPathComponent is taken from [Apple Documentation](https://developer.apple.com/reference/foundation/nsstring/1416528-lastpathcomponent).
Hope to hear the feedback)
=> Debug functionality to AsyncType

.travis.yml, BrightFutures.podspec, Cartfile, Cartfile.resolved, Sources/BrightFutures/Async.swift, Tests/BrightFuturesTests/BrightFuturesTests.swift
This fixes an issue where carthage would fail to build BrightFutures because `Result` version 3.0 was not compiled using swift 3.1.
I also update your podspec file but in the interest of full disclosure I did not test this to make sure it works with CocoaPods.
=> Fixes swift 3.1 compile errors/warnings

Sources/BrightFutures/Result+BrightFutures.swift
Fixes #183. The compile error in Xcode 9.3b4 is gone with this change, and it works in Xcode 9.2.
My understanding of https://bugs.swift.org/browse/SR-7059 is that Swift 4.1 is going to ship with this change being necessary.
=> Explicit Void return type on `analysis(ifSuccess:` block

BrightFutures.podspec, CHANGELOG.md
* Updated podspec and CHANGELOG for 6.0.1
Looks like the other steps to release a new version are tagging, creating a GitHub
release, and pushing an update to Cocoapods.
Anything else?
=> Release 6.0.1

Tests/BrightFuturesTests/BrightFuturesTests.swift
There was one typo in the `f` future name next to the `.onSuccess` callback, and another in the assert error message.
=> Fix the `andThen` test

Sources/BrightFutures/ExecutionContext.swift
This fixes a build error that occurs when building BrightFutures on Linux with Swift 4.2.3
=> localThreadDictionary must be var

Package.swift
Currently you cannot use version 8 with swift package manager v5. I updated the Package.swift file to build the library and specify swift tools version that allows use by swift5.
=> Updated Package.swift to work with swift 5

Sources/BrightFutures/AsyncType+ResultType.swift, Tests/BrightFuturesTests/BrightFuturesTests.swift
Hello.
Thank you for BrightFutures.
In this pull request I added `func map<U>(_ context: @escaping ExecutionContext, keyPath: KeyPath<Value.Value, U>) -> Future<U, Value.Error>`. It is similar to `map` that you already have, but accepts KeyPath instead of a closure.
=> Map by KeyPath

Sources/BrightFutures/AsyncType+ResultType.swift
```sh
% swift -version
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0
```
```sh
% swift build
BrightFutures/Sources/BrightFutures/AsyncType+ResultType.swift:233:54: warning: will never be executed
return mapError(ImmediateExecutionContext) { $0 as! E } // future will never fail, so this map block will never get called
^
BrightFutures/Sources/BrightFutures/AsyncType+ResultType.swift:233:52: note: '$0' is uninhabited, so this function body can never be executed
return mapError(ImmediateExecutionContext) { $0 as! E } // future will never fail, so this map block will never get called
^
BrightFutures/Sources/BrightFutures/AsyncType+ResultType.swift:265:49: warning: will never be executed
return map(ImmediateExecutionContext) { $0 as! T } // …
```
=> Reduce "warning: will never be executed"

Sources/BrightFutures/Future.swift, Tests/BrightFuturesTests/BrightFuturesTests.swift
Hello.
Thank you for BrightFutures.
In this pull request I added `Future.init(error: E, delay: DispatchTimeInterval)`. This function is similar to `Future.init(value: T, delay: DispatchTimeInterval)`.
=> Future.init(error: E, delay: DispatchTimeInterval)
